version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - static_volume:/home/realestkma/app/staticfiles
      - media_volume:/home/realestkma/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    
  redis:
    image: redis:7-alpine
    expose:
      - 6379

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command:  celery -A src worker -l INFO
    env_file:
      - ./.env
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start-flower.sh
    expose:
      - 5555
    env_file:
      - ./.env
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - static_volume:/home/realestkma/app/staticfiles
      - media_volume:/home/realestkma/app/mediafiles
    ports:
      - 8001:80
    depends_on:
      - api
      - flower


volumes:
  postgres_data:
  static_volume: