version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -c gunicorn.conf.py src.wsgi:application
    volumes:
      - static_volume:/home/realestkma/app/staticfiles
      - media_volume:/home/realestkma/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    environment:
      - VIRTUAL_PATH=/
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    
  redis:
    image: redis:7-alpine
    expose:
      - 6379

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command:  celery -A src worker -l INFO
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      - redis

  pika_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /home/realestkma/app/openuser/pika_consumers.py
    restart: always
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start-flower.sh
    restart: on-failure
    expose:
      - 8000
    env_file:
      - ./.env
    environment:
      - VIRTUAL_PATH=/flower/
    depends_on:
      - redis

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8001:80
      # - 443:443
    volumes:
      - static_volume:/home/realestkma/app/staticfiles
      - media_volume:/home/realestkma/app/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api
      - flower


volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme: