############################
# Base image
############################
FROM python:3.10-slim-buster

# working directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# update apt and install needed dependencies
RUN apt update && apt-get -y install netcat

# upgrade pip, copy over requirement file and install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy over entrypoint.sh and mark it as executable
COPY ./entrypoint.sh .
RUN chmod +x /usr/src/app/entrypoint.sh

# copy over the project, make sure to set .dockerignore
# to prevent copying unnecessary files
COPY . .

# run the entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
