############################
# Base image
############################
FROM python3.10:slime-buster as builder

# working directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# copy dependencies and install
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy over the whole project, make sure to set .dockerignore
# to prevent copying unnecessary files
COPY . .
