version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -c gunicorn.conf.py src.wsgi:application
    volumes:
      - static_volume:/home/realestkma/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    
  redis:
    image: redis:7-alpine
    expose:
      - 6379

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command:  celery -A src worker -l INFO
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start-flower.sh
    expose:
      - 5555
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/realestkma/app/staticfiles
    ports:
      - 8001:80
    depends_on:
      - api
      - flower


volumes:
  postgres_data:
  static_volume: