version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -c gunicorn.conf.py src.wsgi:application
    volumes:
      - static_volume:/home/realestkma/app/staticfiles
      - media_volume:/home/realestkma/app/mediafiles
    expose:
      - 8000
    env_file:
      - /home/realestkma/.env.prod
    environment:
      - VIRTUAL_PATH=/

  redis:
    image: redis:7-alpine
    expose:
      - 6379

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command:  celery -A src worker -l INFO
    restart: always
    env_file:
      - /home/realestkma/.env.prod
    depends_on:
      - redis

  pika_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /home/realestkma/app/openuser/pika_consumers.py
    restart: always
    env_file:
      - /home/realestkma/.env.prod
    depends_on:
      - redis
      - celery

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start-flower.sh
    restart: always
    expose:
      - 8000
    env_file:
      - /home/realestkma/.env.prod
    environment:
      - VIRTUAL_PATH=/flower/
    depends_on:
      - redis
      - celery

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/realestkma/app/staticfiles
      - media_volume:/home/realestkma/app/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api
      - flower

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - /home/realestkma/.env.prod
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy


volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme: