# Generated by Django 4.0.5 on 2022-06-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openuser', '0003_alter_user_app_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_app_name',
        ),
    ]
