# Generated by Django 4.0.5 on 2022-08-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openuser', '0006_alter_user_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Undefined', 'Undefined')], default='Undefined', max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
