# Generated by Django 4.0.4 on 2022-09-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openuser', '0009_alter_openusercreator_cid_alter_openusercreator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openusercreator',
            name='username',
            field=models.CharField(blank=True, help_text='Openuser Creator username', max_length=15, null=True, verbose_name='Username'),
        ),
    ]
