# Generated by Django 4.0.4 on 2022-06-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openusercreator',
            name='username',
            field=models.CharField(blank=True, help_text='Creators username', max_length=255, null=True, verbose_name='Username'),
        ),
    ]
