# Generated by Django 4.0.5 on 2022-06-10 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='app_name',
            field=models.CharField(help_text='The name of this Openuser data. Spaces are replaced with underscores', max_length=20, validators=[django.core.validators.RegexValidator(message='Must begin and end with a letter. And can only contain letters, numbers and hyphens', regex='^[a-zA-Z]([\\w -]*[a-zA-Z])?$'), django.core.validators.MinLengthValidator(limit_value=4)], verbose_name='App Name'),
        ),
    ]
