# Generated by Django 4.0.5 on 2022-06-10 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openuser', '0002_alter_user_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='User password', max_length=128, validators=[django.core.validators.MinLengthValidator(limit_value=8), django.core.validators.RegexValidator(inverse_match=True, message='Password cannot contain spaces', regex='\\s')], verbose_name='Password'),
        ),
    ]
