# Generated by Django 4.0.5 on 2022-06-10 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openuser', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text='About me', null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='user',
            name='app_name',
            field=models.CharField(blank=True, help_text='The name of this Openuser data. Spaces are replaced with underscores', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Must begin and end with a letter. And can only contain letters, numbers and hyphens', regex='^[a-zA-Z]([\\w -]*[a-zA-Z])?$'), django.core.validators.MinLengthValidator(limit_value=4)], verbose_name='App Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mugshot',
            field=models.URLField(blank=True, help_text='Users mugshot url', max_length=255, null=True, verbose_name='Mugshot'),
        ),
    ]
