# Generated by Django 4.0.5 on 2022-06-10 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openuser', '0004_alter_user_about_alter_user_app_name_alter_user_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('country_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Country Code')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('state_abbr', models.CharField(blank=True, max_length=5, null=True, verbose_name='State Abbreviation')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal/ZIP')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
