# Generated by Django 4.0.5 on 2022-06-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openuser', '0005_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street'),
        ),
    ]
