# This action deploys my containerized app. Uses docker-compose up to start app

name: CD Deploy (Azure)

on:
  workflow_dispatch:


jobs:
  deploy-app:

    runs-on: self-hosted

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      
      - name: Ping Azure
        run:  ping -c4 azure.microsoft.com
      
      - name: Show docker containers
        run:  docker compose -f docker-compose.prod.yml ps -a

      - name: Run docker compose up
        run:  docker compose -f docker-compose.prod.yml up --detach --build