# This action deploys my containerized app. Uses docker-compose up to start app

name: CD Deploy (Azure)

on:
  workflow_dispatch:


jobs:
  deploy-app:

    runs-on: self-hosted

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      
      - name: Run docker-compose up
        run: docker ps -a