# This action assumes that pytest, pytest-django and other pytest-** dependencies required to test the app is in the requirements.txt file.
# it also makes use of postgresql container service.

name: CI Test


on:
  push:
    branches:
      - main


jobs:
  build-and-test-with-pytest:

    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      
    services:
     postgres:
      image:  postgres:14
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: github_actions
      ports:
        - 5432:5432
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: Test with pytest
        run: |
          pytest